### PR TITLE
👷 chore(ci): refactor tests workflow and bump dependencies to make CI runs work

### PR DESCRIPTION
**Pull request by Horgix**

### CODE REVIEW

**Comment by Horgix** [comment]
This is a **Draft** PR to get the CI running. Don't merge it yet :slightly_smiling_face: I'll mark it as ready for review when it is!

**Comment by Vermeille** [comment]
You. Are. Wonderful.

Thank you so much.

**Comment by Horgix** [comment]
Bumping dependencies actually did the trick. Now tests are running (a couple are failing but that's another thing :slightly_smiling_face: I'll fix 2 of them in another PR, but for the third one I've no idea how to fix it)

**Comment by Horgix** [comment]
Now ready to be merged!

**Comment by Vermeille** [comment]
You rock.

**Pull request merged**
